In [26]:
from pathlib import Path

import pandas as pd
import chardet

In [ ]:
# Paths
DATA_DIR = Path("../data")
RAW_DATA_PATH = DATA_DIR / "raw" / "sales_data.csv"
PROCESSED_DATA_PATH = DATA_DIR / "processed" / "sales_data_cleaned.csv"

# Display Options
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.2f}".format)

In [27]:
try:
    sales_df = pd.read_csv(
        RAW_DATA_PATH,
        sep="\t",
        decimal=",",
        encoding="cp1252",
        low_memory=False
    )
except Exception:
    sales_df = pd.read_excel(
        RAW_DATA_PATH,
        engine="openpyxl"
    )

sales_df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,"2,871.00",2003-02-24,Shipped,1,2,2003,Motorcycles,95,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,"2,765.90",2003-05-07,Shipped,2,5,2003,Motorcycles,95,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,"3,884.34",2003-07-01,Shipped,3,7,2003,Motorcycles,95,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,"3,746.70",2003-08-25,Shipped,3,8,2003,Motorcycles,95,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,"5,205.27",2003-10-10,Shipped,4,10,2003,Motorcycles,95,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [28]:
print(f"Number of Rows    : {sales_df.shape[0]:,}")
print(f"Number of Columns : {sales_df.shape[1]}")

Number of Rows    : 2,823
Number of Columns : 25

In [29]:
sales_df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,"2,871.00",2003-02-24,Shipped,1,2,2003,Motorcycles,95,S10_1678,Land of Toys Inc.,2125557818,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,"2,765.90",2003-05-07,Shipped,2,5,2003,Motorcycles,95,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,"3,884.34",2003-07-01,Shipped,3,7,2003,Motorcycles,95,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,"3,746.70",2003-08-25,Shipped,3,8,2003,Motorcycles,95,S10_1678,Toys4GrownUps.com,6265557265,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,"5,205.27",2003-10-10,Shipped,4,10,2003,Motorcycles,95,S10_1678,Corporate Gift Ideas Co.,6505551386,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [30]:
sales_df.info()

sales_df.describe(include="all").T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   datetime64[ns]
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   object
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(7), object(15)
memory usage: 551.5+ KB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
ORDERNUMBER,"2,823.00",NaN,NaN,NaN,"10,258.73","10,100.00","10,180.00","10,262.00","10,333.50","10,425.00",92.09
QUANTITYORDERED,"2,823.00",NaN,NaN,NaN,35.09,6.00,27.00,35.00,43.00,97.00,9.74
PRICEEACH,"2,823.00",NaN,NaN,NaN,83.66,26.88,68.86,95.70,100.00,100.00,20.17
ORDERLINENUMBER,"2,823.00",NaN,NaN,NaN,6.47,1.00,3.00,6.00,9.00,18.00,4.23
SALES,"2,823.00",NaN,NaN,NaN,"3,553.89",482.13,"2,203.43","3,184.80","4,508.00","14,082.80","1,841.87"
ORDERDATE,2823,NaN,NaN,NaN,2004-05-11 00:16:49.989373056,2003-01-06 00:00:00,2003-11-06 12:00:00,2004-06-15 00:00:00,2004-11-17 12:00:00,2005-05-31 00:00:00,NaN
STATUS,2823,6,Shipped,2617,NaN,NaN,NaN,NaN,NaN,NaN,NaN
QTR_ID,"2,823.00",NaN,NaN,NaN,2.72,1.00,2.00,3.00,4.00,4.00,1.20
MONTH_ID,"2,823.00",NaN,NaN,NaN,7.09,1.00,4.00,8.00,11.00,12.00,3.66
YEAR_ID,"2,823.00",NaN,NaN,NaN,"2,003.82","2,003.00","2,003.00","2,004.00","2,004.00","2,005.00",0.70
PRODUCTLINE,2823,7,Classic Cars,967,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MSRP,"2,823.00",NaN,NaN,NaN,100.72,33.00,68.00,99.00,124.00,214.00,40.19
PRODUCTCODE,2823,109,S18_3232,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CUSTOMERNAME,2823,92,Euro Shopping Channel,259,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PHONE,2823,91,(91) 555 94 44,259,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ADDRESSLINE1,2823,92,"C/ Moralzarzal, 86",259,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ADDRESSLINE2,302,9,Level 3,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CITY,2823,73,Madrid,304,NaN,NaN,NaN,NaN,NaN,NaN,NaN
STATE,1337,16,CA,416,NaN,NaN,NaN,NaN,NaN,NaN,NaN
POSTALCODE,"2,747.00",73.00,"28,034.00",259.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COUNTRY,2823,19,USA,1004,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TERRITORY,1749,3,EMEA,1407,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CONTACTLASTNAME,2823,77,Freyre,259,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CONTACTFIRSTNAME,2823,72,Diego,259,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEALSIZE,2823,3,Medium,1384,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
missing_values = (
    sales_df
    .isna()
    .sum()
    .to_frame(name="Missing Values")
)

missing_values["Percentage"] = (
    missing_values["Missing Values"]
    / len(sales_df)
    * 100
).round(2)

missing_values.sort_values(
    by="Missing Values",
    ascending=False
)

                  Missing Values  Percentage
ADDRESSLINE2                2521       89.30
STATE                       1486       52.64
TERRITORY                   1074       38.04
POSTALCODE                    76        2.69
ORDERNUMBER                    0        0.00
CUSTOMERNAME                   0        0.00
CONTACTFIRSTNAME               0        0.00
CONTACTLASTNAME                0        0.00
COUNTRY                        0        0.00
CITY                           0        0.00
ADDRESSLINE1                   0        0.00
PHONE                          0        0.00
PRODUCTCODE                    0        0.00
QUANTITYORDERED                0        0.00
MSRP                           0        0.00
PRODUCTLINE                    0        0.00
YEAR_ID                        0        0.00
MONTH_ID                       0        0.00
QTR_ID                         0        0.00
STATUS                         0        0.00
ORDERDATE                      0        0.00
SALES                          0        0.00
ORDERLINENUMBER                0        0.00
PRICEEACH                      0        0.00
DEALSIZE                       0        0.00

In [32]:
duplicate_count = sales_df.duplicated().sum()

print(f"Duplicate Records : {duplicate_count}")

Duplicate Records : 0

In [33]:
categorical_columns = sales_df.select_dtypes(include="object").columns

for column in categorical_columns:
    print(f"{column:20} : {sales_df[column].nunique()}")

STATUS               : 6
PRODUCTLINE          : 7
PRODUCTCODE          : 109
CUSTOMERNAME         : 92
PHONE                : 91
ADDRESSLINE1         : 92
ADDRESSLINE2         : 9
CITY                 : 73
STATE                : 16
POSTALCODE           : 73
COUNTRY              : 19
TERRITORY            : 3
CONTACTLASTNAME      : 77
CONTACTFIRSTNAME     : 72
DEALSIZE             : 3

In [34]:
# Data Cleaning
# Remove Duplicate

rows_before = len(sales_df)

sales_df = (
    sales_df
    .drop_duplicates()
    .reset_index(drop=True)
)


rows_after = len(sales_df)

print(f"Duplicate Removed : {rows_before - rows_after}")

# Remove Extra Whitespac
text_columns = sales_df.select_dtypes(include="object").columns

sales_df[text_columns] = sales_df[text_columns].apply(
    lambda column: column.str.strip()
)

# Convert Date
sales_df["ORDERDATE"] = pd.to_datetime(
    sales_df["ORDERDATE"],
    format="%m/%d/%Y %H:%M",
    errors="coerce"
)

sales_df["ORDERDATE"].dtype

sales_df["ORDERDATE"].isna().sum()

numeric_columns = [
    "QUANTITYORDERED",
    "PRICEEACH",
    "ORDERLINENUMBER",
    "SALES",
    "QTR_ID",
    "MONTH_ID",
    "YEAR_ID",
    "MSRP"
]

sales_df[numeric_columns].dtypes

categorical_columns = [
    "STATUS",
    "PRODUCTLINE",
    "COUNTRY",
    "TERRITORY",
    "DEALSIZE"
]

for column in categorical_columns:
    print(f"\n{column}")
    print(sales_df[column].sort_values().unique())

sales_df.isna().sum()

Duplicate Removed : 0

STATUS
['Cancelled' 'Disputed' 'In Process' 'On Hold' 'Resolved' 'Shipped']

PRODUCTLINE
['Classic Cars' 'Motorcycles' 'Planes' 'Ships' 'Trains' 'Trucks and Buses'
 'Vintage Cars']

COUNTRY
['Australia' 'Austria' 'Belgium' 'Canada' 'Denmark' 'Finland' 'France'
 'Germany' 'Ireland' 'Italy' 'Japan' 'Norway' 'Philippines' 'Singapore'
 'Spain' 'Sweden' 'Switzerland' 'UK' 'USA']

TERRITORY
['APAC' 'EMEA' 'Japan' nan]

DEALSIZE
['Large' 'Medium' 'Small']

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE               1004
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE          2358
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [35]:
print(sales_df.shape)

sales_df.head()

(2823, 25)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,"2,871.00",2003-02-24,Shipped,1,2,2003,Motorcycles,95,S10_1678,Land of Toys Inc.,NaN,897 Long Airport Avenue,NaN,NYC,NY,NaN,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,"2,765.90",2003-05-07,Shipped,2,5,2003,Motorcycles,95,S10_1678,Reims Collectables,26.47.1555,59 rue de l'Abbaye,NaN,Reims,NaN,NaN,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,"3,884.34",2003-07-01,Shipped,3,7,2003,Motorcycles,95,S10_1678,Lyon Souveniers,+33 1 46 62 7555,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,NaN,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,"3,746.70",2003-08-25,Shipped,3,8,2003,Motorcycles,95,S10_1678,Toys4GrownUps.com,NaN,78934 Hillside Dr.,NaN,Pasadena,CA,NaN,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,"5,205.27",2003-10-10,Shipped,4,10,2003,Motorcycles,95,S10_1678,Corporate Gift Ideas Co.,NaN,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [36]:
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

sales_df.to_csv(
    PROCESSED_DATA_PATH,
    index=False
)

print(f"Dataset exported to:\n{PROCESSED_DATA_PATH}")

Dataset exported to:
..\data\processed\sales_data_cleaned.csv